### ISSUE TITLE
JFontSize seems not working on template made with Template Creator CK

### ISSUE THREAD

**Issue by alleusai** [betweenbrain/jFontSize-Module#19]
Hello!
I have installed the jFontSize on Joomla 3.3.6 The template is made with Template Creator CK. When I click on the A- A A+ , I don't see any changes to the fonts on the website.
When I inspect the browser and I click on the A+, the font size in the inspect mood increase but not on the screen. No errors are logged to console.
As you can see jquery (v 1.11.1) is loaded before jfontsize.

Could you give me a hint?

Thanks in advance,
Alessandro

![image](https://cloud.githubusercontent.com/assets/7127245/5877425/cd02c9ea-a31f-11e4-8993-53ec5b61e5fe.png)

**Comment by betweenbrain** [comment]
Hello,

Can you inspect the page source of the elements that are not changing and see if inline styles have been applied? See https://github.com/betweenbrain/jFontSize-Module/issues/6#issuecomment-36133310 and https://github.com/betweenbrain/jFontSize-Module/issues/9#issuecomment-47020481 for further details if that is the case.

Best,
Matt

**Comment by alleusai** [comment]
It was!
Thank you so much Matt.

Alessandro

**Comment by betweenbrain** [comment]
You're welcome!
